name: Download Resonite
description: Download Resonite headless client using SteamCMD with caching

inputs:
  resonite_branch:
    description: 'Resonite branch (headless or prerelease)'
    required: false
    default: 'headless'
  steam_username:
    description: 'Steam username'
    required: true
  steam_password:
    description: 'Steam password'
    required: true
  headless_password:
    description: 'Headless password'
    required: true

outputs:
  resonite_version:
    description: 'Downloaded Resonite version'
    value: ${{ steps.versions.outputs.resonite_version }}
  cache_key:
    description: 'Cache key for Resonite Headless files'
    value: ${{ steps.versions.outputs.cache_key }}

runs:
  using: composite
  steps:
    - name: Restore Resonite cache
      id: cache-restore
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ./Resonite/Headless
          ./native-libs
        key: resonite-headless-${{ inputs.resonite_branch }}-dummy
        restore-keys: |
          resonite-headless-${{ inputs.resonite_branch }}-

    - name: Download Resonite
      shell: bash
      env:
        STEAM_USERNAME: ${{ inputs.steam_username }}
        STEAM_PASSWORD: ${{ inputs.steam_password }}
        HEADLESS_PASSWORD: ${{ inputs.headless_password }}
      run: |
        if [ "${{ inputs.resonite_branch }}" == "prerelease" ]; then
          USE_PRERELEASE=true bash ${GITHUB_WORKSPACE}/scripts/download-resonite.sh
        else
          bash ${GITHUB_WORKSPACE}/scripts/download-resonite.sh
        fi

    - name: Read Resonite Version
      id: versions
      shell: bash
      env:
        RESONITE_BRANCH: ${{ inputs.resonite_branch }}
      run: |
        RESO_VERSION=$(cat ./Resonite/Headless/Build.version)
        echo "resonite_version=$RESO_VERSION" >> $GITHUB_OUTPUT
        echo "cache_key=resonite-headless-${RESONITE_BRANCH}-${RESO_VERSION}" >> $GITHUB_OUTPUT

    - name: Save Resonite cache
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ./Resonite/Headless
          ./native-libs
        key: ${{ steps.versions.outputs.cache_key }}
